### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by cjdoris** [cjdoris/PythonCall.jl#1]
# `Py<Wrapper>`
- [x] `PyIterable`
- [x] `PyList`
- [x] `PyDict`
- [x] `PySet`
- [x] `PyBuffer`
  - [ ] General parsing of format strings.
  - [ ] Unaligned types.
  - [ ] Byte-reversed types.
- [x] `PyArray`
  - [x] Support the numpy array interface (`__array__`, `__array_interface__`).
  - [ ] Allow conversion to/from tuples containing python objects.
- [x] `PyPandasDataFrame`
  - [x] Tables interface
  - [x] TableTraits interface
  - [x] Customise column types and index
  - [ ] Convert `pandas.core.indexes.range.RangeIndex` to a `StepRange{Int}`?
- [x] `PyIO`
  - [x] Currently limited to byte-based IO and extremely slow. Perhaps need to manually buffer each way?
- [x] `PyObjectArray <: AbstractArray{PyObject}`, represented as an array of `CPyPtr`, used by default as output of `pyjulia(::AbstractArray).__array__()`.

# `pyjulia`
- [x] Sequence interface (tuples and vectors)
- [x] Buffer protocol (strided arrays)
- [x] Numpy array protocol (`__array_interface__`)
- [x] Numpy array conversion (`__array__`) returning `PyObjectArray` by default unless `__array_interface__` already supported.
- [ ] Generalize `pytypestrformat` to work on any type.
- [x] Mapping interface (dicts, named tuples?)
- [x] Set interface (sets)
- [x] Number interface
- [x] IO interface (IO=IOBase, then subclasses for raw, buffered and text IO)
- [x] An argument parsing function or macro
- [x] Separate `pyjlraw` from `pyjl`
- [ ] Have a `BufferedIterator` which iterates over 1024 (say) values at a time and saves them as a buffer of `PyObject`.

# `pyconvert`
- [x] dates, times
- [x] ctypes
- [x] to named tuple
- [x] arrays (buffer protocol, array interface, and `__array__`)
- [x] IO
- [x] numbers
- [x] numpy scalars (`np.float32` etc)

# Others
- [x] README
- [x] Documentation
- [x] Logo
- [ ] Testing & CI
- [x] Migrate CI away from Travis. GitHub Actions?
- [x] Move configuration (finding libpython) all to run-time & dynamically load/cache function pointers as required.
- [x] Multimedia display (MIMEs and corresponding `_repr_MIME_` methods from ipython)
- [x] Hook into Julia documentation system
- [x] `QT_PLUGIN_PATH` hack
- [x] GUI event loops to support interactive plotting (e.g. with matplotlib)
- [x] `@pyeval`, `@pyexec`, `py"..."` for calling `pyeval` and `pyexec` with Julia value interpolation
- [x] `?some_python_function` should show the function name and signature
- [x] Add GIL manipulation functions (`pygiloff`, `pygilon`, etc)
- [x] When running inside an IPython kernel, change the default output display to go the kernel
- [ ] When running inside an IJulia kernel, change `sys.stdout` to go the the kernel
- [ ] When running inside an IPython or IJulia kernel, start up the other kind of kernel and link them together.
